// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/auction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	BidValue       int32                  `protobuf:"varint,2,opt,name=bid_value,json=bidValue,proto3" json:"bid_value,omitempty"`
	BandwidthValue int32                  `protobuf:"varint,3,opt,name=bandwidth_value,json=bandwidthValue,proto3" json:"bandwidth_value,omitempty"`
	AuctionRound   int32                  `protobuf:"varint,4,opt,name=auction_round,json=auctionRound,proto3" json:"auction_round,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BidRequest) GetBidValue() int32 {
	if x != nil {
		return x.BidValue
	}
	return 0
}

func (x *BidRequest) GetBandwidthValue() int32 {
	if x != nil {
		return x.BandwidthValue
	}
	return 0
}

func (x *BidRequest) GetAuctionRound() int32 {
	if x != nil {
		return x.AuctionRound
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Won           bool                   `protobuf:"varint,1,opt,name=won,proto3" json:"won,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_auction_proto protoreflect.FileDescriptor

const file_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auction.proto\x12\tauctionpb\"\x8b\x01\n" +
	"\n" +
	"BidRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1b\n" +
	"\tbid_value\x18\x02 \x01(\x05R\bbidValue\x12'\n" +
	"\x0fbandwidth_value\x18\x03 \x01(\x05R\x0ebandwidthValue\x12#\n" +
	"\rauction_round\x18\x04 \x01(\x05R\fauctionRound\"9\n" +
	"\vBidResponse\x12\x10\n" +
	"\x03won\x18\x01 \x01(\bR\x03won\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2D\n" +
	"\aAuction\x129\n" +
	"\bPlaceBid\x12\x15.auctionpb.BidRequest\x1a\x16.auctionpb.BidResponseBEZCgithub.com/honhaoyuan0/FYP-Observability-on-SDN/Simplify_Demo/protob\x06proto3"

var (
	file_proto_auction_proto_rawDescOnce sync.Once
	file_proto_auction_proto_rawDescData []byte
)

func file_proto_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)))
	})
	return file_proto_auction_proto_rawDescData
}

var file_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auction_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: auctionpb.BidRequest
	(*BidResponse)(nil), // 1: auctionpb.BidResponse
}
var file_proto_auction_proto_depIdxs = []int32{
	0, // 0: auctionpb.Auction.PlaceBid:input_type -> auctionpb.BidRequest
	1, // 1: auctionpb.Auction.PlaceBid:output_type -> auctionpb.BidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auction_proto_init() }
func file_proto_auction_proto_init() {
	if File_proto_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_proto = out.File
	file_proto_auction_proto_goTypes = nil
	file_proto_auction_proto_depIdxs = nil
}
